### ISSUE TITLE
Create DataDescriptionValue interface

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_vis#17]
https://github.com/phovea/phovea_vis/pull/13#discussion_r92191072

```
 function defaultColor(value: any)
```
We're using an `any` in heatmap.ts because we don't have a type that actually contains just the information we need. Better to be more precise.

**Comment by sgratzl** [comment]
implemented in the core already

**Comment by mccalluc** [comment]
This line is unchanged in master: https://github.com/phovea/phovea_vis/blob/master/src/heatmap.ts#L19.

**Comment by sgratzl** [comment]
but not in the develop branch ...
