### ISSUE TITLE
Allow other columns to be defaults for scatter plot

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_vis#5]
From @thinkh: https://github.com/Caleydo/caleydo.github.io/issues/161

- web_bundle version: 0.0.1
- browser version: Firefox 49.0.1
- OS: Windows 10
### Reproducer:

http://phovea.caleydo.org/tutorials/frame.html?demo_getting_started/demo_4

### Observed behavior:

![web_bundle_tutorial_demo3](https://cloud.githubusercontent.com/assets/5851088/18877472/a6c0da1a-84cd-11e6-987e-d0c2a30f8fb2.PNG)
### Expected behavior:

A different default selection from the two drop downs that give a better impression, e.g. as follows:

![web_bundle_tutorial_demo3_expected](https://cloud.githubusercontent.com/assets/5851088/18877513/c563e750-84cd-11e6-867b-50a95bcb3f5d.PNG)

Right now, to get a different set of axes you need to

1. [Extend the options](https://github.com/Caleydo/caleydo_vis/blob/master/scatterplot.ts#L16)
2. [Replace the default selectedIndex](https://github.com/Caleydo/caleydo_vis/blob/master/scatterplot.ts#L45)
3. Use the new options in the tutorial

... but it seems that this is something that should be easier to configure.

**Comment by sgratzl** [comment]
use https://github.com/datavisyn/phovea_vis_scatterplot/blob/master/src/index.ts#L36 instead

**Comment by mccalluc** [comment]
Can the existing scatterplot be removed? Can documentation refer to https://github.com/datavisyn/phovea_vis_scatterplot? How would a new user know that it exists, and is the best thing to use?

**Comment by sgratzl** [comment]
invalid: removed
