### ISSUE TITLE
Encode missing values in heatmaps

### ISSUE THREAD

**Issue by mstreit** [phovea/phovea_vis#57]
Coming from https://github.com/Caleydo/taggle/issues/316

In the rendered version we want to indicate missing values by a dash and via a provided color.
The texture-based heat map version should only use the color to indicate missing values (because the cells are usually much smaller).

The missing value color should set as a parameter.

**Comment by thinkh** [comment]
So far it only works for the heatmap canvas renderer. @sgratzl will fix the DOM renderer soon.

![grafik](https://cloud.githubusercontent.com/assets/5851088/26410242/fda1ee00-40a2-11e7-92fc-a7c4b00efbee.png)

**Comment by sgratzl** [comment]
without any changes I get for the dom renderer:
![2017-05-26 08_26_01-einstellungen](https://cloud.githubusercontent.com/assets/4129778/26483411/165a3f6a-41ed-11e7-9f37-5821593145aa.png)
