### ISSUE TITLE
heatmaps with a negative+positive range should be blue-white-red

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_vis#6]
version: e1fed65c5727386a29587fe813a28e3f5b74d5f7
url: http://phovea.caleydo.org/tutorials/frame.html?demo_data_structures/demo_5

### Observed behavior:

The colors only range from blue to white

### Expected behavior:

From talking with @thinkh and looking at https://github.com/Caleydo/caleydo_vis/blob/master/heatmap.ts#L22, I think the color range we expect is blue-white-red. Perhaps the NaN throws it off? But I don't think I have ever seen a blue-white-red heat map here, so I don't think it's as simple as that.

**Comment by mccalluc** [comment]
```
  if (r[0] < 0 && r[1] > 0) {
    //use a symmetric range
    return ['blue', 'white', 'red'];
  }
```
Where is this used?
```
    if (arrEqual(colors, ['black', 'white'])) {
      //default scale
    } else if (arrEqual(colors, ['white', 'red'])) {
      args.palette = 'white_red';
    } else if (arrEqual(colors, ['blue', 'white', 'red'])) {
      args.palette = 'blue_white_red';
    }
```
This could be confusing: the array could be misleading, since we end up just checking for equality... Except I haven't found where the 'blue_white_red' string is used. Will try tracing this in the JS...

**Comment by sgratzl** [comment]
https://github.com/Caleydo/caleydo_vis/blob/master/heatmap.ts#L40

at this line I think a middle `0` is missing.

**Comment by sgratzl** [comment]
is this still valid with the latest develop branch?

**Comment by mccalluc** [comment]
I would like to see the correct behavior demonstrated in the tutorial before closing this.
