### ISSUE TITLE
Add axes to scatter plots

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_vis#7]
@thinkh, on https://github.com/Caleydo/caleydo.github.io/pull/137#issuecomment-247617844:

> According to the [scatterplot source code](https://github.com/Caleydo/caleydo_vis/blob/master/scatterplot.ts) doesn't provide axes. However, there is an [axis module](https://github.com/Caleydo/caleydo_vis/blob/master/axis.ts) that you can use with a vector. It would be great if you can extend the scatterplot about an option flag to enable/disable the axes.

**Comment by sgratzl** [comment]
deprecated use https://github.com/datavisyn/phovea_vis_scatterplot instead

**Comment by mccalluc** [comment]
Can the existing scatterplot be removed? Can documentation refer to https://github.com/datavisyn/phovea_vis_scatterplot? How would a new user know that it exists, and is the best thing to use?

**Comment by sgratzl** [comment]
invalid: removed
