### ISSUE TITLE
Add selection highlighting / brushing to scatterplots

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_vis#8]
copy from: https://github.com/Caleydo/caleydo.github.io/issues/162

- web_bundle version: 0.0.1
- browser version: Firefox 49.0.1
- OS: Windows 10
### Reproducer:

Open [Demo 3](http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?3) and [Demo 4](http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?4)
### Observed behavior:

Selection highlight is missing in scatter plots and cannot select items in scatterplots.

![missing_selection_highlight](https://cloud.githubusercontent.com/assets/5851088/18877671/34294ff4-84ce-11e6-8138-16512713d8cb.PNG)
### Expected behavior:

Dots in scatterplot should be selectable and highlighted.
If a table row is selected the dot should be highlighted in the scatterplot.

**Comment by mccalluc** [comment]
@ngehlenborg : My guess is that for large datasets, we need not just the ability to link individual datapoints, but to drag a rect to select all the points in a region? That might be better handled as a distinct issue, but I want to clarify scope.

**Comment by sgratzl** [comment]
deprecated use https://github.com/datavisyn/phovea_vis_scatterplot instead

**Comment by mccalluc** [comment]
Can the existing scatterplot be removed? Can documentation refer to https://github.com/datavisyn/phovea_vis_scatterplot? How would a new user know that it exists, and is the best thing to use?

**Comment by sgratzl** [comment]
invalid: removed
